#Numpy Arrays & Operations:

In [ ]:
import numpy as np

In [ ]:
arr_1D = np.array([5,7,9,11],dtype=float)
print(arr_1D)
print(arr_1D.shape)
print(arr_1D.size)

[ 5.  7.  9. 11.]
(4,)
4


In [ ]:
arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="str")
print(arr_2D)
print(arr_2D.shape)
print(arr_2D.size)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
(3, 3)
9


In [ ]:
arr_3D=np.array([[[4,5,6],[7,8,9]],[[3,5,7],[8,7,9]],[[1,2,3],[5,6,7]]])
print(arr_3D)
print(arr_3D.shape)
print(arr_3D.size)

[[[4 5 6]
  [7 8 9]]

 [[3 5 7]
  [8 7 9]]

 [[1 2 3]
  [5 6 7]]]
(3, 2, 3)
18


##Add,Sub,Mul,Div:


In [ ]:
a=np.array([4,5,6])
b=np.array([3,7,9])
s=np.multiply(a,b)
p=np.round(np.divide(a,b),2)
print(a+b)
print(a-b)
print(s)
print(p)

[ 7 12 15]
[ 1 -2 -3]
[12 35 54]
[1.33 0.71 0.67]


##Mean,Sum,Std:

In [ ]:
arr=np.array([5,6,8,9,10])
sum=np.sum(arr)
mean=np.mean(arr)
std=np.round(np.std(arr),2)
print("sum:",sum)
print("mean:",mean)
print("standard deviation:",std)

sum: 38
mean: 7.6
standard deviation: 1.85


##Reshape,Arange,Linspace:

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
reshape=arr.reshape(3,3)
print(reshape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr=np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
max=np.max(arr)
min=np.min(arr)
print(max)
print(min)

11
0
